deepp/deepp.landing/Models/Events.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace deepp.landing.Models
{
    public class Events
    {
        public string id { get; set; }
        public string title { get; set; }
        public string date { get; set; }
        public string start { get; set; }
        public string end { get; set; }
        public string url { get; set; }

        public bool allDay { get; set; }
    }
}

deepp/deepp.landing/Controllers/EventController.cs
using deepp.Service;
using Repository.Pattern.UnitOfWork;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcPaging;
using deepp.Entities.Models;
namespace deepp.landing.Controllers
{
    public class EventController : Controller
    {
        private readonly IEventService _eventServic;
        private readonly IUnitOfWork _unitOfWork;
        public EventController(IUnitOfWork unitOfWork, IEventService eventeServic)
        {
            _eventServic = eventeServic;
            _unitOfWork = unitOfWork;
        }
        /// <summary>
        /// GetAll
        /// </summary>
        /// <returns></returns>
        public ActionResult GetAll()
        {
            var InstituteId = Sessions.InstituteId;
            var Event = _eventServic.AllActiveEvent(InstituteId);
            return PartialView("GetPartialEvent", Event);
        }
        public ActionResult EventPartialList(int? page, string searchItem)
        {
            var InstituteId = Sessions.InstituteId;
            ViewData["searchItem"] = searchItem;
            const int defaultPageSize = 10;
            var currentPageIndex = page.HasValue ? page.Value : 1;
            var events = (IList<Event>)_eventServic.AllActiveEvent(InstituteId).ToList();
            events = string.IsNullOrWhiteSpace(searchItem) ? events.ToPagedList(currentPageIndex, defaultPageSize) : events.Where(p => p.EventTitle.ToLower().Contains(searchItem.ToLower())).ToPagedList(currentPageIndex, defaultPageSize);
            return PartialView("_EventPartialList",(IPagedList<Event>) events);
        }
        /// <summary>
        /// GetAllWithDetails
        /// </summary>
        /// <returns></returns>
        public ActionResult GetAllWithDetails()
        {
            var InstituteId = Sessions.InstituteId;
            var Event = _eventServic.GetGlobalEventByCurrentDateWithenStartEndDate(InstituteId,true);
            return View("EventList", Event);
        }
        /// <summary>
        /// GetAllWithGrid
        /// </summary>
        /// <returns></returns>
        public ActionResult GetAllWithGrid(int? page, string searchItem)
        {
           

            var InstituteId = Sessions.InstituteId;
            ViewData["searchItem"] = searchItem;
            const int defaultPageSize = 4;
            var currentPageIndex = page.HasValue ? page.Value : 1;
            var events = (IList<Event>)_eventServic.GetAllEvent(InstituteId).ToList();
            events = string.IsNullOrWhiteSpace(searchItem) ? events.ToPagedList(currentPageIndex, defaultPageSize) : events.Where(p => p.EventTitle.ToLower().Contains(searchItem.ToLower())).ToPagedList(currentPageIndex, defaultPageSize);
            return PartialView("EventGrid", (IPagedList<Event>)events);
        }
        
        /// <summary>
        /// Details
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Details(int? id)
        {
            var InstituteId = Sessions.InstituteId;
            if (id == null)
            {
                var EventMax = _eventServic.GetGlobalEventByCurrentDateWithenStartEndDate(InstituteId,true).FirstOrDefault();
                return View("SingleEvent", EventMax);
            }
            else
            {
                var Event = _eventServic.GetEventById(Convert.ToInt32(id));
                if (Event.Image != null)
                {
                    Event.Image.ImageBinaryData = null;
                }
                return View("SingleEvent", Event);
            }


        }
        //protected override void Dispose(bool disdeepping)
        //{
        //    if (disdeepping)
        //    {
        //        _unitOfWork.Dispose();
        //    }
        //    base.Dispose(disdeepping);
        //}



    }
}

deepp/deepp.landing/Controllers/GalleryController.cs
using deepp.Service;
using Repository.Pattern.UnitOfWork;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace deepp.landing.Controllers
{
    public class GalleryController : Controller
    {
        private readonly IGalleryService _galleryServic;
        private readonly IUnitOfWork _unitOfWork;
        public GalleryController(IUnitOfWork unitOfWork, IGalleryService galleryServic)
        {
            _galleryServic = galleryServic;
            _unitOfWork = unitOfWork;
        }


        public ActionResult GetPartialGallery()
        {

            var InstituteId = Sessions.InstituteId;
          //  var gallery = _galleryServic.GetGlobalGalleryByCurrentDateWithenStartEndDateTop10(InstituteId,true);
            var gallery = _galleryServic.GetGalleryDefault(InstituteId, true);
            
           // var gallery = _galleryServic.Ge(InstituteId,true);
            return PartialView("GalleryList", gallery);
        }

        public ActionResult GetAllGallery()
        {

            var InstituteId = Sessions.InstituteId;
            var gallery = _galleryServic.GetActiveGallery(InstituteId);
            return View("GalleryGrid", gallery);
        }

        public ActionResult GetGalleryById(int Id)
        {

            var InstituteId = Sessions.InstituteId;
            var gallery = _galleryServic.GetGalleryById(InstituteId, Id);
            return View("GalleryListById", gallery);
        }
        //protected override void Dispose(bool disdeepping)
        //{
        //    if (disdeepping)
        //    {
        //        _unitOfWork.Dispose();
        //    }
        //    base.Dispose(disdeepping);
        //}


    }
}

deepp/deepp.landing/Views/Event/EventGrid.cshtml
@using MvcPaging
@model IPagedList<deepp.Entities.Models.Event>
@{
    ViewBag.Title = "News & Event";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style type="text/css">
    .tab-nav {
        width: 370px;
    }
</style>

<main id="main-content">
    <!-- Main Section -->
    <div class="main-section">
        <div class="container">
            <div class="row">
                <div class="page-content">
                    <!-- Page Section -->
                    <div style="margin-top: 0px;margin-bottom: 0px;border-top: 0px #e0e0e0 solid;border-bottom: 0px #e0e0e0 solid;" class="page-section ">
                        <!-- Container Start -->
                        <div class="container">
                            <div class="row">
                                <div class="section-fullwidth">
                                    <div class="element-size-100">
                                        <div class="cs-heading-sec col-md-12">
                                            <div style="border-bottom:1px solid #ebebe9 !important;" class="inner-sec">
                                                <h1 style="color: !important; font-size: 30px !important; text-align:left;;">
                                                    News & Events
                                                </h1>
                                                @*<div style="color: !important; text-align: left;">
                                                        Paneling regarding rabbit ahead dolorously soothingly ouch unbound excluding sewed
                                                    </div>*@
                                            </div>
                                        </div>
                                    </div><div class="element-size-100">
                                        <div class="col-md-12 main-filter">
                                            <nav class="filter-nav">
                                                <ul class="cs-filter-menu pull-left">
                                                    <li><span class="sortby">Sort by</span></li>
                                                    <li>
                                                        <div class="slect-area">
                                                            <i class="icon-location7"></i>
                                                            <form name="filterable" method="get" action="#">
                                                                <select onchange="this.form.submit()" name="filter_category">
                                                                    <option value="News">News</option>
                                                                    <option value="Event">Event</option>
                                                                    <option value="Notice">Notice</option>
                                                                </select>
                                                            </form>
                                                        </div>
                                                    </li>
                                                </ul>
                                                <ul class="grid-filter">
                                                    <li class="">
                                                        <a href="?page_switch=list"><i class="icon-th-list"></i></a>
                                                    </li>
                                                    <li class="">
                                                        <a href="?page_switch=grid"><i class="icon-grid4"></i></a>
                                                    </li>
                                                </ul>
                                            </nav>
                                        </div>
                                        <div class="cs-events events-listing col-md-12">
                                            @*<script src="https://maps.googleapis.com/maps/api/js?sensor=true" type="text/javascript"></script>*@
                                            @foreach (var item in Model)
                                            {
                                                <article class="deeppt-702">
                                                    <div class="date-time">
                                                        <span>@item.EventStartAt.Value.ToString("MMM")</span>
                                                        <strong>@item.EventStartAt.Value.Day</strong>
                                                    </div>
                                                    <section>
                                                        <div class="text">

                                                            @*<span>
                                                                    <a rel="tag" href="http://uoce.chimpgroup.com/event-category/raoundtable/">RAOUNDTABLE</a><a rel="tag" href="http://uoce.chimpgroup.com/event-category/science/">Science</a>
                                                                </span>*@

                                                            <h2>
                                                                @Html.ActionLink(@item.EventTitle, "Details", "Event", new { id = item.Id }, null)
                                                            </h2>
                                                            <ul class="deeppt-options">

                                                                <li>
                                                                    <i class="icon-target5"></i>
                                                                    <span class="cs-event-time">All Day </span>
                                                                </li>
                                                                <li>
                                                                    <i class="icon-location6"></i>
                                                                    @item.EventLocation
                                                                </li>

                                                            </ul>
                                                            <ul class="categories">
                                                                <li>
                                                                    <i class="icon-users5"></i>Contact Person:
                                                                    @item.ContactPerson

                                                                </li>
                                                            </ul>
                                                        </div>
                                                        @*<div class="right-side">
                                                            @if (item.IsActive)
                                                            {
                                                                <a class="free-btn" href="#">Open</a>
                                                            }
                                                            else
                                                            {
                                                                <a class="cancle-btn" href="#">Close</a>
                                                            }
                                                        </div>*@

                                                    </section>
                                                </article>
                                            }


                                        </div>
                                        <div class="col-md-12">
                                            <nav class="pagination">
                                                @*<div class="pager">*@
                                                @Html.Raw(Html.Pager(
                 new Options
                 {
                     PageSize = Model.PageSize,
                     TotalItemCount = Model.TotalItemCount,
                     CurrentPage = Model.PageNumber,
                     ItemTexts = new ItemTexts() { Next = "Next", Previous = "Previous" },
                     ItemIcon = new ItemIcon() { First = "icon-backward", Previous = "icon-chevron-left", Next = "icon-chevron-right", Last = "icon-forward" },
                     TooltipTitles = new TooltipTitles() { Next = "Next page {0}", Previous = "Previous page {0}", Page = "Go to page {0}" },
                     Size = Size.normal,
                     Alignment = Alignment.centered,
                     IsShowControls = true,
                     IsShowFirstLast = true,
                     IsShowPages = true
                 }, new { searchItem = ViewData["searchItem"] }))

                                            </nav>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <aside class="page-sidebar">
                    @*<div class="widget cs_ads_banner">
                            <div class="cs_banner_section">
                                <a target="_blank" href="" id="cs_banner_clicks276833028" onclick="cs_banner_click_count_plus('http://uoce.chimpgroup.com/wp-admin/admin-ajax.php', '276833028')"><img alt="Sidebar" src="http://uoce.chimpgroup.com/wp-content/uploads/add-img.jpg"></a>
                            </div>
                        </div>*@
                    <div class="widget widget_tabs">
                        <div class="widget element-size-100 widget_tabs">
                            <div class="widget-section-title">
                                <h6></h6>
                            </div>
                            <ul class="tab-nav">
                                <li class="active"><a href="#tab1" data-toggle="tab"><i class="icon-user9"> Notice</i></a></li>
                                <li class=""><a href="#tab2" data-toggle="tab"><i class="icon-tag7">News & Events</i></a></li>
                                @*<li class=""><a href="#tab3" data-toggle="tab"><i class="icon-folder5">Acdemic Caleder</i></a></li>*@
                            </ul>
                            <div class="tab-content">
                                <div class="tab-pane fade in active tabs news" id="tab1">
                                    <ul>

                                        @{Html.RenderAction("GetAll", "Notice");}
                                    </ul>
                                    <a href="~/Notice/GetAllWithGrid" class="viewall-btn csbg-hovercolor"><i class="icon-angle-double-right"></i> More Notice</a>
                                </div>
                                <div class="tab-pane fade tabs news" id="tab2">


                                    @{Html.RenderAction("GetAll", "Event");}

                                    <a href="~/Event/GetAllWithGrid" class="viewall-btn csbg-hovercolor"><i class="icon-angle-double-right"></i> More News</a>
                                </div>
                            </div>
                        </div>
                    </div>


                    <div class="widget widget_gallery">
                        <div class="widget-section-title"><h6>Photo Gallery</h6></div>
                        <ul class="gallery-list">
                            @{Html.RenderAction("GetPartialGallery", "Gallery");}
                        </ul>
                    </div>
                </aside>
            </div>
        </div>
    </div>
</main>


@*@model IEnumerable<deepp.Entities.Models.Event>
    @{
        ViewBag.Title = "Event Grid";
    }
    <div class="page-header">
        <div class="row">
            <div class="col-md-6 col-sm-6">
                <h2 class="page-title">News & Event</h2>
            </div> <!-- /.col-md-6 -->
            <div class="col-md-6 col-sm-6 hidden-xs back-home">
                @Html.ActionLink("← Go back Home", "Index", "Home", new { }, null)
            </div> <!-- /.col-md-6 -->
        </div> <!-- /.row -->
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="box-content">
                <h4 class="widget-title"><span>Notice</span></h4>
                @{Html.RenderAction("GetAll", "Notice");}
                @Html.ActionLink("More Notice", "GetAllWithGrid", "Notice", new { }, new { @class = "btn btn-default-alt btn-sm pull-right" })
            </div> <!-- /.box-content -->
            <div class="box-content">
                <h4 class="widget-title"><span>Gallery</span></h4>
                @{Html.RenderAction("GetPartialGallery", "Gallery");}
            </div> <!-- /.box-content -->
        </div> <!-- /.col-md-4 -->
        <div class="col-md-8">
            @{Html.RenderPartial("GetPartialEventsWithGridDetails", Model);}
        </div>
    </div>*@

deepp/deepp.landing/Views/Event/EventList.cshtml
@model IEnumerable<deepp.Entities.Models.Event>
@{
    ViewBag.Title = "EventList";
}

<div class="container">
    <div class="row">
        <!-- Here begin Main Content -->
        <div class="col-md-8">
            <div class="row">
                <div class="col-md-12">
                    
                    @{Html.RenderPartial("GetPartialEventWithDetails", Model);}
                </div> <!-- /.col-md-12 -->
            </div> <!-- /.row -->
            <div class="row">
                <div class="col-md-12">
                    <div class="load-more-btn">
                        <a href="#">Click here to load more events</a>
                    </div>
                </div> <!-- /.col-md-12 -->
            </div> <!-- /.row -->
        </div> <!-- /.col-md-8 -->
        <!-- Here begin Sidebar -->
        <div class="col-md-4">
            <div class="widget-main">
                <div class="widget-main-title">
                    <h4 class="widget-title btn-link"> @Html.ActionLink("Events Lidt", "GetAllWithGrid", "Event", new { }, null)</h4>
                </div> <!-- /.widget-main-title -->
                <div class="widget-inner">
                    @{Html.RenderPartial("GetPartialEvent",Model);}

                  
                </div> <!-- /.widget-inner -->
            </div> <!-- /.widget-main -->
            <div class="widget-main">
                <div class="widget-main-title">
                    <h4 class="widget-title">Our Gallery</h4>
                </div>
                <div class="widget-inner">
                    <div class="gallery-small-thumbs clearfix">
                        <div class="thumb-small-gallery">
                            <a class="fancybox" rel="gallery1" href="~/images/gallery/gallery1.jpg" title="Gallery Tittle One">
                                <img src="~/images/gallery/gallery-small-thumb1.jpg" alt="" />
                            </a>
                        </div>
                        <div class="thumb-small-gallery">
                            <a class="fancybox" rel="gallery1" href="./images/gallery/gallery2.jpg" title="Gallery Tittle One">
                                <img src="~/images/gallery/gallery-small-thumb2.jpg" alt="" />
                            </a>
                        </div>
                        <div class="thumb-small-gallery">
                            <a class="fancybox" rel="gallery1" href="./images/gallery/gallery3.jpg" title="Gallery Tittle One">
                                <img src="./images/gallery/gallery-small-thumb3.jpg" alt="" />
                            </a>
                        </div>
                        <div class="thumb-small-gallery">
                            <a class="fancybox" rel="gallery1" href="~/images/gallery/gallery4.jpg" title="Gallery Tittle One">
                                <img src="~/images/gallery/gallery-small-thumb4.jpg" alt="" />
                            </a>
                        </div>
                        <div class="thumb-small-gallery">
                            <a class="fancybox" rel="gallery1" href="~/images/gallery/gallery5.jpg" title="Gallery Tittle One">
                                <img src="~/images/gallery/gallery-small-thumb5.jpg" alt="" />
                            </a>
                        </div>
                        <div class="thumb-small-gallery">
                            <a class="fancybox" rel="gallery1" href="~/images/gallery/gallery6.jpg" title="Gallery Tittle One">
                                <img src="~/images/gallery/gallery-small-thumb6.jpg" alt="" />
                            </a>
                        </div>
                        <div class="thumb-small-gallery">
                            <a class="fancybox" rel="gallery1" href="~/images/gallery/gallery7.jpg" title="Gallery Tittle One">
                                <img src="~/images/gallery/gallery-small-thumb7.jpg" alt="" />
                            </a>
                        </div>
                        <div class="thumb-small-gallery">
                            <a class="fancybox" rel="gallery1" href="~/images/gallery/gallery8.jpg" title="Gallery Tittle One">
                                <img src="~/images/gallery/gallery-small-thumb8.jpg" alt="" />
                            </a>
                        </div>
                    </div> <!-- /.galler-small-thumbs -->
                </div> <!-- /.widget-inner -->
            </div> <!-- /.widget-main -->
        </div> <!-- /.col-md-4 -->

    </div> <!-- /.row -->
</div> <!-- /.container -->

deepp/deepp.landing/Views/Event/GetPartialEvent.cshtml
@model IEnumerable<deepp.Entities.Models.Event>
<div class="cs-events events-listing">
    @{
        int i = 0;

        foreach (var item in Model)
        {


            @*<span class="cat">
                    <a href="http://uoce.chimpgroup.com/category/masonry/" rel="tag">Masonry</a>
                </span>*@
            @*<a href="http://uoce.chimpgroup.com/law-degree-is-the-most-valuable-degree/">Law degree is the Most valuable degree</a>*@
            @*@Html.ActionLink(@item.EventTitle, "Details", "Event", new { id = item.Id }, null)
                <span class="info">

                    <time datetime="2008-02-14">@item.EventStartAt.Value.Day, @item.EventStartAt.Value.ToString("MMM")</time> <span> @item.EventLocation</span>
                </span>*@
            <article class="deeppt-702">
                <div class="date-time">
                    <span>@item.EventStartAt.Value.ToString("MMM")</span>
                    <strong>@item.EventStartAt.Value.Day</strong>
                </div>
                <section>
                    <div class="text">

                        <h2>
                            @Html.ActionLink(@item.EventTitle, "Details", "Event", new { id = item.Id }, null)
                        </h2>
                        <ul class="deeppt-options">

                            <li>
                                <i class="icon-location6"></i>
                                @item.EventLocation
                            </li>

                        </ul>
                    </div>

                </section>
            </article>


            i++;
            if (i == 3)
            {
                break;
            }

            @*<div class="item">

                    <figure class="cs-eventslider">
                        <a href="#"><img src="~/assets/img/UOCE-Events-Posts-02-340x255.jpg" alt=""></a>
                        <figcaption>
                            <time datetime="2008-02-14 20:00"><i class="icon-clock"></i>@item.EventStartAt.Value.Day, @item.EventStartAt.Value.ToString("MMM")</time>
                            <div class="event-caption">
                                <h6>@Html.ActionLink(@item.EventTitle, "Details", "Event", new { id = item.Id }, null)</h6>
                                <span> @item.EventLocation</span>
                            </div>
                        </figcaption>
                    </figure>
                </div>*@
        }

    }
</div>
@*<div class="event-small-list clearfix">

        <div class="calendar-small">
            <span class="s-month">@item.EventStartAt.Value.ToString("MMM")</span>
            <span class="s-date">@item.EventStartAt.Value.Day</span>
        </div>
        <div class="event-small-details">

            @if (@item.EventTitle.Length >= 40)
            {
                <h5 class="event-small-title">@Html.ActionLink(@item.EventTitle.Substring(0, 40), "Details", "Event", new { id = item.Id }, null)</h5>
                <p class="event-small-meta small-text">
                    <span class="event-place small-text"><i class="fa fa-globe"></i>@item.EventLocation</span>
                    <span class="event-date small-text"><i class="fa fa-calendar-o"></i>@item.EventStartAt.Value.ToString("MMM") @item.EventStartAt.Value.Day, @item.EventStartAt.Value.Year</span>

                </p>
            }
            else
            {
                <h5 class="event-small-title">@Html.ActionLink(@item.EventTitle, "Details", "Event", new { id = item.Id }, null)</h5>
                <p class="event-small-meta small-text">
                    <span class="event-place small-text"><i class="fa fa-globe"></i>@item.EventLocation</span>
                    <span class="event-date small-text"><i class="fa fa-calendar-o"></i>@item.EventStartAt.Value.ToString("MMM") @item.EventStartAt.Value.Day, @item.EventStartAt.Value.Year</span>

                </p>
            }
        </div>
    </div>*@

deepp/deepp.landing/Views/Event/GetPartialEventWithDetails.cshtml
@model IEnumerable<deepp.Entities.Models.Event>
@foreach (var item in Model)
{


    <div class="list-event-item">
        <div class="box-content-inner clearfix">

            <div class="list-event-header">

                <div class="view-details lightBtn">
                    @Html.ActionLink("View Details", "Details", "Event", new { id = item.Id }, null)
                </div>
            </div>
            <h5 class="event-title">
                @Html.ActionLink(@item.EventTitle, "Details", "Event", new { id = item.Id }, null)
            </h5>

            @if (@item.EventBody.Length > 100)
            { <p>
                @item.EventBody.Substring(1, 100)....
            </p>

            }
            else
            {
                <p>   @item.EventBody;</p>
            }

        </div>
    </div>

}

deepp/deepp.landing/Views/Event/_EventPartialList.cshtml
@model IEnumerable<deepp.Entities.Models.Teacher>


@foreach (var item in Model)
{
    <article class="deeppt-702">
        <div class="date-time">
            <span>Dec</span>
            <strong>15</strong>
        </div>
        <section>
            <div class="text">

                <span>
                    <a rel="tag" href="http://uoce.chimpgroup.com/event-category/raoundtable/">RAOUNDTABLE</a><a rel="tag" href="http://uoce.chimpgroup.com/event-category/science/">Science</a>
                </span>

                <h2>
                    <a href="http://uoce.chimpgroup.com/events/international-conference-on-environmental-prism/">
                        International Conference on environmental pris
                    </a>
                </h2>
                <ul class="deeppt-options">

                    <li>
                        <i class="icon-target5"></i>
                        <span class="cs-event-time">All Day                                                            </span>
                    </li>
                    <li>
                        <i class="icon-location6"></i>
                        179 York Way, Holloway, N7 9LN
                    </li>

                </ul>
                <ul class="categories">
                    <li>
                        <i class="icon-users5"></i>Speakers:
                        REGINALD PHILIP

                    </li>
                </ul>
            </div>
            <div class="right-side">
                <a class="cancle-btn" href="#">Closed</a>
            </div>
        </section>
    </article>
}