deepp/deepp.landing/Controllers/GalleryController.cs
using deepp.Service;
using Repository.Pattern.UnitOfWork;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace deepp.landing.Controllers
{
    public class GalleryController : Controller
    {
        private readonly IGalleryService _galleryServic;
        private readonly IUnitOfWork _unitOfWork;
        public GalleryController(IUnitOfWork unitOfWork, IGalleryService galleryServic)
        {
            _galleryServic = galleryServic;
            _unitOfWork = unitOfWork;
        }


        public ActionResult GetPartialGallery()
        {

            var InstituteId = Sessions.InstituteId;
          //  var gallery = _galleryServic.GetGlobalGalleryByCurrentDateWithenStartEndDateTop10(InstituteId,true);
            var gallery = _galleryServic.GetGalleryDefault(InstituteId, true);
            
           // var gallery = _galleryServic.Ge(InstituteId,true);
            return PartialView("GalleryList", gallery);
        }

        public ActionResult GetAllGallery()
        {

            var InstituteId = Sessions.InstituteId;
            var gallery = _galleryServic.GetActiveGallery(InstituteId);
            return View("GalleryGrid", gallery);
        }

        public ActionResult GetGalleryById(int Id)
        {

            var InstituteId = Sessions.InstituteId;
            var gallery = _galleryServic.GetGalleryById(InstituteId, Id);
            return View("GalleryListById", gallery);
        }
        //protected override void Dispose(bool disdeepping)
        //{
        //    if (disdeepping)
        //    {
        //        _unitOfWork.Dispose();
        //    }
        //    base.Dispose(disdeepping);
        //}


    }
}

deepp/deepp.landing/Controllers/NoticeController.cs
using deepp.Entities.Models;
using deepp.Service;
using deepp.Service.ViewModels;
using Repository.Pattern.UnitOfWork;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcPaging;
namespace deepp.landing.Controllers
{
    public class NoticeController : Controller
    {

        private readonly INoticeService _noticeServic;
        private readonly ITestimonialService _testimonialService;
        private readonly IVmLandingService _vmLandingService;
        private readonly IUnitOfWork _unitOfWork;
        public NoticeController(IUnitOfWork unitOfWork, INoticeService noticeServic, IVmLandingService vmLandingService, ITestimonialService testimonialService)
        {
            _noticeServic = noticeServic;
            _testimonialService = testimonialService;
            _vmLandingService = vmLandingService;
            _unitOfWork = unitOfWork;
        }
        public ActionResult GetAll()
        {
            var InstituteId = Sessions.InstituteId;
            var notice = _noticeServic.GetActiveNotice(InstituteId);
            return PartialView("GetPartialNotice", notice);
        }
        /// <summary>
        /// Get all Notice List
        /// </summary>
        /// <returns></returns>
        public ActionResult GetAllWithDetails()
        {
            var InstituteId = Sessions.InstituteId;
            var notice = _noticeServic.GetGlobalNoticeByCurrentDateWithenStartEndDate(InstituteId, true);
            return View("NoticeList", notice);
        }
        public ActionResult GetAllWithGrid(int? page, string searchItem)
        {
            var InstituteId = Sessions.InstituteId;
            ViewData["searchItem"] = searchItem;
            const int defaultPageSize = 4;
            var currentPageIndex = page.HasValue ? page.Value : 1;
            //var notice = _noticeServic.GetActiveNotice(InstituteId);

            var notices = (IList<Notice>)_noticeServic.GetActiveNotice(InstituteId).ToList();
            notices = string.IsNullOrWhiteSpace(searchItem) ? notices.ToPagedList(currentPageIndex, defaultPageSize) : notices.Where(p => p.NoticeTitle.ToLower().Contains(searchItem.ToLower())).ToPagedList(currentPageIndex, defaultPageSize);

            return View("NoticeGrid", (IPagedList<Notice>)notices);
        }
        public ActionResult GetUrgentNotice()
        {
            var InstituteId = Sessions.InstituteId;
            var notice = _noticeServic.GetActiveNotice(InstituteId);
            return PartialView("NoticeUrgent", notice);
        }
        // GET: /Notice/Details/5
        public ActionResult Details(int? id)
        {
            var InstituteId = Sessions.InstituteId;
            if (id == null)
            {
                var noticeMax = _noticeServic.GetGlobalNoticeByCurrentDateWithenStartEndDate(InstituteId, true).FirstOrDefault();
                return View("SingleNotice", noticeMax);
            }
            else
            {
                var notice = _noticeServic.GetNoticeById(Convert.ToInt32(id));
                return View("SingleNotice", notice);
            }
        }

        public ActionResult ActiveTeacherNotice(int? page, string searchItem)
        {
          
            var InstituteId = Sessions.InstituteId;
            ViewData["searchItem"] = searchItem;
            const int defaultPageSize = 4;
            var currentPageIndex = page.HasValue ? page.Value : 1;        
            var notices = (IList<Notice>)_noticeServic.GetActiveNoticeByTypeId(InstituteId, (int)deepp.utility.NoticeType.Teacher).ToList();
            notices = string.IsNullOrWhiteSpace(searchItem) ? notices.ToPagedList(currentPageIndex, defaultPageSize) : notices.Where(p => p.NoticeTitle.ToLower().Contains(searchItem.ToLower())).ToPagedList(currentPageIndex, defaultPageSize);

            return View("ActiveTeacherNotice", (IPagedList<Notice>)notices);
        }
        public ActionResult ActiveStudentNotice(int? page, string searchItem)
        {
          
            var InstituteId = Sessions.InstituteId;
            ViewData["searchItem"] = searchItem;
            const int defaultPageSize = 4;
            var currentPageIndex = page.HasValue ? page.Value : 1;
            var notices = (IList<Notice>)_noticeServic.GetActiveNoticeByTypeId(InstituteId, (int)deepp.utility.NoticeType.Student).ToList();
            notices = string.IsNullOrWhiteSpace(searchItem) ? notices.ToPagedList(currentPageIndex, defaultPageSize) : notices.Where(p => p.NoticeTitle.ToLower().Contains(searchItem.ToLower())).ToPagedList(currentPageIndex, defaultPageSize);

            return View("ActiveStudentNotice", (IPagedList<Notice>)notices);
        }
        public ActionResult ActiveEmployeeNotice(int? page, string searchItem)
        {
           
            var InstituteId = Sessions.InstituteId;
            ViewData["searchItem"] = searchItem;
            const int defaultPageSize = 4;
            var currentPageIndex = page.HasValue ? page.Value : 1;
            var notices = (IList<Notice>)_noticeServic.GetActiveNoticeByTypeId(InstituteId, (int)deepp.utility.NoticeType.Employee).ToList();
            notices = string.IsNullOrWhiteSpace(searchItem) ? notices.ToPagedList(currentPageIndex, defaultPageSize) : notices.Where(p => p.NoticeTitle.ToLower().Contains(searchItem.ToLower())).ToPagedList(currentPageIndex, defaultPageSize);

            return View("ActiveEmployeeNotice", (IPagedList<Notice>)notices);
        }

        //protected override void Dispose(bool disdeepping)
        //{
        //    if (disdeepping)
        //    {
        //        _unitOfWork.Dispose();
        //    }
        //    base.Dispose(disdeepping);
        //}
    }
}

deepp/deepp.landing/Views/Gallery/GalleryGrid.cshtml
@model IEnumerable<deepp.Entities.Models.Gallery>
@{
    ViewBag.Title = "Gallery ";
}
<main id="main-content">
    <!-- Main Section -->
    <div class="main-section">
        <div class="container">
            <div class="row">
                <div class="page-content">
                    <!-- Page Section -->
                    <div class="page-section " style="margin-top: 0px;margin-bottom: 0px;border-top: 0px #e0e0e0 solid;border-bottom: 0px #e0e0e0 solid;">
                        <!-- Container Start -->
                        <div class="container">
                            <div class="row">
                                <div class="section-fullwidth">
                                    @*<div class="element-size-100">
                                            <div style="background-image:url(); color:; background-color:;" class="cs-holder lightbox  col-md-12">
                                                <img src="http://uoce.chimpgroup.com/wp-content/uploads/multimedia.jpg" alt="multimedia" class="alignnone size-full wp-image-345">
                                            </div>
                                        </div>*@
                                    <div class="element-size-100">
                                        <div style="background-image:url(); color:; background-color:;" class="cs-holder lightbox  col-md-12">
                                            <h1>Photo Gallery</h1>
                                            @*In 1789, then Archishop John Carroll secured the deed to 60 acres of land on a hilltop overlooking the village of Georgetown and the Potomac River. Over the centuries, the college he created has developed into one of the top research universities in the country, known for its relevance and diversity in the heart of Washington, D.C.*@
                                        </div>
                                    </div>
                                    <div class="element-size-100">
                                        <div class="cs-gallery plain">
                                            <div class="row">
                                                @foreach (var item in Model){
                                                    <article class="col-md-4">
                                                        <figure>
                                                            @if (item.Image != null)
                            {
                                                                <a href="~/Gallery/GetGalleryById?id=@item.Id">
                                                                    @*<img src="http://uoce.chimpgroup.com/wp-content/uploads/gallery-8.jpg" alt="">*@
                                                                    <img class="attachment-cause-thumb-4col wp-deeppt-image" src="../image/GetImage?id=@item.Id&refCode=19&isThumbnail=false" alt="">
                                                                </a>
                                                            }
                                                            <figcaption>
                                                                <span>@*5 Photos*@</span>
                                                            </figcaption>
                                                        </figure>
                                                        <h6> @Html.ActionLink(@item.GalleryTitle, "GetGalleryById", new { id = item.Id })</h6>
                                                    </article>
                                                    }

                                                <div class="clear"></div>
                                            </div>
                                        </div>
                                        <!-- Latest Video End -->
                                        <!--<div class="clear"></div>
                                        </div>-->
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>            <aside class="page-sidebar">
                    <div class="widget cs_ads_banner"><div class="cs_banner_section"><a onclick="cs_banner_click_count_plus('http://uoce.chimpgroup.com/wp-admin/admin-ajax.php', '276833028')" id="cs_banner_clicks276833028" href="" target="_blank"><img src="http://uoce.chimpgroup.com/wp-content/uploads/add-img.jpg" alt="Sidebar"></a></div></div><div class="widget widget_calendar">
                        <div class="widget-section-title"><h6>Calendar</h6></div><div id="calendar_wrap" class="calendar_wrap">
                            <table id="wp-calendar">
                                <caption>December 2017</caption>
                                <thead>
                                    <tr>
                                        <th scope="col" title="Monday">M</th>
                                        <th scope="col" title="Tuesday">T</th>
                                        <th scope="col" title="Wednesday">W</th>
                                        <th scope="col" title="Thursday">T</th>
                                        <th scope="col" title="Friday">F</th>
                                        <th scope="col" title="Saturday">S</th>
                                        <th scope="col" title="Sunday">S</th>
                                    </tr>
                                </thead>

                                <tfoot>
                                    <tr>
                                        <td colspan="3" id="prev"><a href="http://uoce.chimpgroup.com/2015/06/">« Jun</a></td>
                                        <td class="pad">&nbsp;</td>
                                        <td colspan="3" id="next" class="pad">&nbsp;</td>
                                    </tr>
                                </tfoot>

                                <tbody>
                                    <tr>
                                        <td colspan="4" class="pad">&nbsp;</td>
                                        <td>1</td>
                                        <td>2</td>
                                        <td>3</td>
                                    </tr>
                                    <tr>
                                        <td>4</td>
                                        <td>5</td>
                                        <td>6</td>
                                        <td>7</td>
                                        <td>8</td>
                                        <td>9</td>
                                        <td>10</td>
                                    </tr>
                                    <tr>
                                        <td>11</td>
                                        <td>12</td>
                                        <td>13</td>
                                        <td>14</td>
                                        <td>15</td>
                                        <td>16</td>
                                        <td>17</td>
                                    </tr>
                                    <tr>
                                        <td>18</td>
                                        <td>19</td>
                                        <td>20</td>
                                        <td>21</td>
                                        <td id="today">22</td>
                                        <td>23</td>
                                        <td>24</td>
                                    </tr>
                                    <tr>
                                        <td>25</td>
                                        <td>26</td>
                                        <td>27</td>
                                        <td>28</td>
                                        <td>29</td>
                                        <td>30</td>
                                        <td>31</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </aside>
            </div>
        </div>
    </div>
</main>


<script src="~/assets/js/vendor/jquery-1.12.0.min.js"></script>
<script type="text/javascript">
    jQuery(window).load(function () {
        $portfolio = jQuery('.portfolio-items');
        $portfolio.isotope({
            itemSelector: 'li',
            layoutMode: 'fitRows'
        });
        $portfolio_selectors = jQuery('.portfolio-filter &gt;li&gt;a');
        $portfolio_selectors.on('click', function () {
            $portfolio_selectors.removeClass('active');
            jQuery(this).addClass('active');
            var selector = jQuery(this).attr('data-filter');
            $portfolio.isotope({ filter: selector });
            return false;
        });
    });


</script>

@*<div class="page-header">
        <div class="row">
            <div class="col-md-6 col-sm-6">
                <h2 class="page-title">Gallery</h2>
            </div> <!-- /.col-md-6 -->
            <div class="col-md-6 col-sm-6 hidden-xs back-home">
                @Html.ActionLink("← Go back Home", "Index", "Home", new { }, null)
            </div> <!-- /.col-md-6 -->
        </div> <!-- /.row -->
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="box-content">
                <h4 class="widget-title"><span>Notice</span></h4>
                @{Html.RenderAction("GetAll", "Notice");}
                @Html.ActionLink("More Notice", "GetAllWithGrid", "Notice", new { }, new { @class = "btn btn-default-alt btn-sm pull-right" })
            </div> <!-- /.box-content -->
        </div> <!-- /.col-md-4 -->
        <div class="col-md-8">
            <div class="box-content">
                @foreach (var item in Model)
                {
                    <div class="col-md-6 col-sm-6 deeppt-grid">
                        <div class="deeppt-thumb">
                            @if (item.Image != null)
                            {
                                <a href="@Url.Action("GetGalleryById", new { Id = item.Id })">
                                    <img class="attachment-cause-thumb-4col wp-deeppt-image" src="../image/GetImage?id=@item.Id&refCode=19&isThumbnail=false">
                                </a>
                            }
                        </div> <!-- /.deeppt-thumb -->
                        <div class="deeppt-content">
                            <p class="deeppt-meta">@item.GallerySubtitle</p>
                            <h4 class="deeppt-title">@Html.ActionLink(@item.GalleryTitle, "GetGalleryById", new { id = item.Id })</h4>

                        </div> <!-- /.deeppt-content -->
                    </div>
                }
            </div>
            </div>
    </div>*@

deepp/deepp.landing/Views/Gallery/GalleryList.cshtml
@model deepp.Entities.Models.Gallery
@{
    ViewBag.Title = "Gallery List";
}
<ul class="gallery-list">


    @foreach (var item in Model.Images)
    {

        if (item != null)
        {
            <li>
                <img src="/image/GetImage?id=@item.RefPrimaryKey&refCode=19&isThumbnail=true">
            </li>
        }
    }

    @*<li><a target="_blank" title="Halloween 2014 at Envato in Melbourne" href="https://www.flickr.com/photos/52617155@N08/15647274066/"><img alt="Halloween 2014 at Envato in Melbourne" src="https://farm4.staticflickr.com/3940/15647274066_2ee48c3fe9_s.jpg"></a></li> *@




</ul>

deepp/deepp.landing/Views/Gallery/GalleryListById.cshtml
@model deepp.Entities.Models.Gallery
@{
    ViewBag.Title = "Gallery ";
}

<main id="main-content">
    <!-- Main Section -->
    <div class="main-section">
        <section style="margin:0 0 20px 0;" class="page-section">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <section id="portfolio-section">
                            <div class="wrap-pad first">
                                <div class="row">
                                    <div class="cs-gallery classic-gallery col-md-12">
                                        <ul class="portfolio-items isotope" style="deeppition: relative; overflow: hidden; height: 414px;">
                                            @{ int i = 0;
                                               int j=0;
                                             foreach (var item in Model.Images)
                                             {
                                                 string pixel = i + "px";
                                                <li class="portfolio-item id_@item.Id col-md-3 isotope-item" style="deeppition: absolute; left: 0px; top: 0px; transform: translate3d(@pixel, 0px, 0px);">
                                                    <div class="item-main">
                                                        <div class="portfolio-image">
                                                            <figure>
                                                                <img src="/image/GetImageById?id=@item.Id&refCode=17" alt="gallery image" title="@item.ImageCaption">
                                                                <figcaption>
                                                                    <ul class="gallery clearfix"></ul>
                                                                    <ul class="gallery clearfix">
                                                                        <a href="~/image/GetImageById?id=@item.Id&refCode=17" rel="prettyPhoto[myGallery]" data-rel="prettyPhoto[@j]" title="@item.ImageCaption.">
                                                                            <i class="icon-plus8"></i>
                                                                        </a>
                                                                    </ul>
                                                                </figcaption>
                                                            </figure>


                                                        </div>
                                                    </div>
                                                </li>
                                                 pixel = "";
                                                 j = j + 1;
                                                 i = i + 270;
                                             }
                                            }

                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
        </section>

        <script type="text/javascript">
            jQuery(window).load(function () {
                $portfolio = jQuery('.portfolio-items');
                $portfolio.isotope({
                    itemSelector: 'li',
                    layoutMode: 'fitRows'
                });
                $portfolio_selectors = jQuery('.portfolio-filter &gt;li&gt;a');
                $portfolio_selectors.on('click', function () {
                    $portfolio_selectors.removeClass('active');
                    jQuery(this).addClass('active');
                    var selector = jQuery(this).attr('data-filter');
                    $portfolio.isotope({ filter: selector });
                    return false;
                });
            });


        </script>
        <!--Footer-->

    </div>
</main>

@*<div class="page-header">
        <div class="row">
            <div class="col-md-6 col-sm-6">
                <h2 class="page-title">@Model.GalleryTitle</h2>
            </div> <!-- /.col-md-6 -->
            <div class="col-md-6 col-sm-6 hidden-xs back-home">
                @Html.ActionLink("← Go back Home", "Index", "Home", new { }, null)
            </div> <!-- /.col-md-6 -->
        </div> <!-- /.row -->
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="box-content">
                <h4 class="widget-title"><span>Notice</span></h4>
                @{Html.RenderAction("GetAll", "Notice");}
                @Html.ActionLink("More Notice", "GetAllWithGrid", "Notice", new { }, new { @class = "btn btn-default-alt btn-sm pull-right" })
            </div> <!-- /.box-content -->
        </div> <!-- /.col-md-4 -->
        <div class="col-md-8">
            <div class="box-content">
                @foreach (var item in Model.Images)
                {
                    <div class="event-list">
                        <div class="event-thumb">
                            <img width="240" height="192" class="attachment-event-thumb wp-deeppt-image" src="/image/GetImageById?id=@item.Id&refCode=17">
                        </div> <!-- /.event-thumb -->

                        <div class="event-content">
                            <p>@item.ImageCaption</p>
                            <div class="clearfix"></div>
                        </div> <!-- /.event-content -->
                    </div>
                }
            </div>
        </div>
    </div>*@